config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "lists#index"
  resources :lists
  resources :tasks do
    member do
      patch :complete
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :tasks
  validates :title, uniqueness: { scope: :user_id }, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list
  default_scope { order(:done, :created_at) }
  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  add_flash_types :danger
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :find_list, except: [:index, :new, :create]

  def index
    @lists = List.all
  end

  def new; end

  def show; end

  def edit; end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to root_path
    else
      redirect_to root_path, danger: "Such list already exist"
    end
  end

  def update
    if @list.update(list_params)
      redirect_to root_path
    else
      redirect_to edit_list_path, danger: "Such list already exist"
    end
  end

  def destroy
    @list.destroy

    redirect_to root_path
  end

  private

  def find_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:title).merge(user_id: current_user.id)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, except: [:index, :new, :create]

  def index
    @task = Task.all
  end

  def new; end

  def show; end

  def edit; end

  def complete
    @task.toggle!(:done)

    redirect_to list_path(@task.list_id)
  end

  def create
    @task = Task.create(task_params)

    redirect_to list_path(@task.list_id)
  end

  def update
    @task.update(task_params)

    redirect_to list_path(@task.list_id)
  end

  def destroy
    @task.destroy

    redirect_to list_path(@task.list_id)
  end

  private

  def find_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :done, :list_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def strike_link(d)
    link_to d.title, complete_task_path(d), method: :patch
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="raw">
        <div class="col-md-2"></div>
        <div class="col-md-8">
          <% flash.each do |name, msg| %>
          <div class="alert alert-<%= name %>">
            <%= msg %>
          </div>
          <% end %>
          <%= yield %>
        </div>
        <div class="col-md-2"></div>
      </div>
      <% if user_signed_in? %>
        <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
      <% end %>
    </div>
  </body>
</html>

app/views/lists/_new.html.erb
<div class="form-inline">
  <%= form_with model: List.new do |f| %>
    <%= f.text_field :title, class: "form-control",
                          placeholder: "Enter new list name", required: true %>
    <%= f.submit "Save", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/lists/edit.html.erb
<%= form_with model: @list do |f| %>
  <div class="form-group">
    <%= f.label "Enter your changes" %><br>
    <%= f.text_field :title, class: "form-control", required: true %>
  </div>
  <%= f.submit "Save", class: "btn btn-primary" %>
  <%= link_to "Back", root_path, class: "btn btn-light" %>
<% end %>

app/views/lists/index.html.erb
<h3>To do list</h3>
<ul class="list-group">
  <% current_user.lists.each do |d| %>
  <li class="list-group-item">
	  <span class="name"><%= link_to d.title, list_path(d) %></span>
		  <button class="btn btn-default btn-xs pull-right remove-item">
        <%= link_to '', list_path(d), method: :delete,
        data: { confirm: 'Are you sure?' }, class: 'glyphicon glyphicon-remove' %>
      </button>
      <button class="btn btn-default btn-xs pull-right edit-item">
        <%= link_to '', edit_list_path(d), class: 'glyphicon glyphicon-cog' %>
      </button>
  </li>
  <% end %>
</ul>
<%= render 'new' %>

app/views/lists/show.html.erb
<h3>What to do?</h3>
<%= render 'tasks/show' %><br>
<%= render 'tasks/new' %><br>
<%= link_to "See all lists", root_path, class: "btn btn-primary btn-sm btn-block" %>

app/views/tasks/_new.html.erb
<div class="form-inline">
  <%= form_with model: Task.new  do |f| %>
    <%= f.hidden_field :list_id, value: params[:id] %>
    <%= f.text_field :title, class: "form-control",
          placeholder: "Enter what to do", required: true %>
    <%= f.submit "Save", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/tasks/_show.html.erb
<ul class="list-group">
  <% @list.tasks.each do |d| %>
  <li class="list-group-item">
    <% if d.done %>
      <span class="name"><strike><%= strike_link(d) %></strike></span>
    <% else %>
      <%= strike_link(d) %>
    <% end %>
    <button class="btn btn-default btn-xs pull-right remove-item">
      <%= link_to '', task_path(d), method: :delete,
        data: { confirm: 'Are you sure?' }, class: 'glyphicon glyphicon-remove'%>
    </button>
    <button class="btn btn-default btn-xs pull-right edit-item">
      <%= link_to '', edit_task_path(d), class: 'glyphicon glyphicon-cog' %>
    </button>
  </li>
  <% end %>
</ul>

app/views/tasks/edit.html.erb
<%= form_with model: @task  do |f| %>
  <div class="form-group">
    <%= f.label "Enter your changes" %>
    <%= f.text_field :title, class: "form-control", required: true %><br>
    <%= f.collection_select :list_id, current_user.lists.all, :id, :title, { prompt: 'Choose list' },
    { class: "form-control", required: true } %>
  </div>
    <%= f.submit "Save", class: "btn btn-primary" %>
    <%= link_to "Back", list_path(@task.list_id), class: "btn btn-light" %>
<% end %>